name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the commit hash
        id: commit_hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t l1zail/podarochnaya-frontend:${{ env.COMMIT_HASH }} .

      - name: Push Docker image
        run: |
          docker push l1zail/podarochnaya-frontend:${{ env.COMMIT_HASH }}

      - name: Tag Docker image as latest
        run: |
          docker tag l1zail/podarochnaya-frontend:${{ env.COMMIT_HASH }} l1zail/podarochnaya-frontend:latest

      - name: Push Docker image as latest
        run: |
          docker push l1zail/podarochnaya-frontend:latest